### ISSUE TITLE
chatbot object has no attribute 'set_trainer'

### ISSUE THREAD

**Issue by ghost** [dineshjoshy/Chatbot_Project#1]
hi mr.dinesh.I am facing problem with this training code.after executing it it appears as "chatbot object has no attribute 'set_trainer'".please resolve this

**Comment by ghost** [comment]
> 
> 
> hi mr.dinesh.I am facing problem with this training code.after executing it it appears as "chatbot object has no attribute 'set_trainer'".please resolve this

    Use following 
    trainer = ListTrainer(chatbot)

**Comment by ghost** [comment]
Thank u, its resolved now,.

**Comment by Manav1918** [comment]
I have d same issue. I have used it as u said. But now second line is showing same error.
In     chatbot.train(chatbot) 
Chatbot has no attribute train
